### ISSUE TITLE
Translate into another language

### ISSUE THREAD

**Issue by bishiboosh** [henrymyers/lorembarnak#4]
Hi, sorry to use the Github issues for that, but I couldn't find any way to contact you. I really like the idea, and wanted to port it to another language (namely, Kotlin). Are you ok with this ? You can close this issue after answering (or close it right away and answer me via the email in my github profile). Thanks !

(je suis français donc le mail peut etre en fr ou en mais je voulais faire l'issue en anglais)

**Comment by henrymyers** [comment]
No problem at all, that would be great! Honestly anyone is welcome to port it to any other language or propose/make improvements 😊 

I can leave this issue open for a while. Let me know when you're done and I'll link to your repo in the readme!

**Comment by dmorissette** [comment]
I would advise adding a proper open source license to the project, which would address this type of question by making it clear that porting the code and other reuses of the code are permitted and encouraged.  (If that is indeed your intention, since just posting code on github does not make it open source and does not give proper permissions to reuse/copy/modify the code)

My suggestion/preference would be the MIT license (https://choosealicense.com/licenses/mit/), but as the original author and owner of the copyright you get to choose the one you like.

P.S. Nice project, I like it.  :)

**Comment by henrymyers** [comment]
It's actually specified in `package.json` (and clearly displayed on NPM), but I didn't even notice that Github didn't detect it. I'll add a `LICENSE` file. Thanks for bringing this up 👍

**Comment by henrymyers** [comment]
Closing this issue, but @bishiboosh please comment here or open up a new issue when you're done 😄
